# Stage 1: Build Stage
FROM node:18-alpine AS build

# Create and set the working directory
WORKDIR /usr/src/app

# Copy the package.json and package-lock.json to install dependencies
COPY package*.json ./

# Install only production dependencies
RUN npm install --production

# Copy the entire source code to the container
COPY . .

# Stage 2: Production Stage
FROM node:18-alpine

# Create and set the working directory for the production stage
WORKDIR /usr/src/app

# Copy only the necessary files from the build stage
COPY --from=build /usr/src/app /usr/src/app

# Expose the port the app runs on
EXPOSE 4000 4001

# Command to run the app
CMD ["npm", "start"]
